### ISSUE TITLE
[NDS-27] Consultar sedes

### ISSUE THREAD

**Issue by DavidC0rtes** [DavidC0rtes/ds2#48]
En el panel de gestión de sedes del  sistema como administrador quiero poder visualizar las sedes existentes,  para visualizar las sedes del sistema.

 
Las sedes deben tener los siguientes campos: 

- NIT

- Dirección

- Teléfono 

- Código del restaurante

- ~Productos disponibles en la sede~

**Escenario 1**: Consultar sede: Cuando se ingrese al panel de gestión de sedes, se desplegara una lista con las sedes y sus características.

**Comment by DavidC0rtes** [comment]
creo que en la tabla el NIT, ni el telefono

**Comment by daveybtw** [comment]
Hay que modificar la entidad pues no hay esos campos, yo intente agregarlos cuando estaba realizando la historia de usuario pero cada vez que alguien corria otra version se modificaba entonces toca modificarlo en todas las versiones.

**Comment by daveybtw** [comment]
Lo mismo lo de productos disponibles

**Comment by DavidC0rtes** [comment]
Lo de la disponibilidad, en la reunión que hicimos se cuadró que toca hacerlo por sedes, también por eso puse lo de seleccionar la sede, para que funcione hay que modificar el modelo porque como lo tenemos es para unidades "globales" toca crear otra tabla que sea como `disponibilidad-sede` y que tenga `(id, id_sede, id_producto, cantidad)` se me ocurre así

**Comment by DavidC0rtes** [comment]
@alejandro1403 @JoseAHC-UV por ahora, para no borrar el esquema de la bd cada que se hagan cambios pongamos dentro del ormconfig.yml, el valor synchronize en falso

**Comment by DavidC0rtes** [comment]
> Lo de la disponibilidad, en la reunión que hicimos se cuadró que toca hacerlo por sedes, también por eso puse lo de seleccionar la sede, para que funcione hay que modificar el modelo porque como lo tenemos es para unidades "globales" toca crear otra tabla que sea como `disponibilidad-sede` y que tenga `(id, id_sede, id_producto, cantidad)` se me ocurre así

Esto realmente aplica para consultar productos, no para consultar sedes, no creo que sea necesario mostrar los productos que hay la verdad

**Comment by daveybtw** [comment]
Si, iba a comentar lo mismo, aplica para producto no para sede, igual yo ya cambie esta historia de usuario con los datos que faltaban en el último pull request.
